/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spotticketing;

/**
 *
 * @author AQUEEL
 */
public class java extends javax.swing.JFrame {

    /**
     * Creates new form java
     */
    public java() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory(null).createEntityManager();
        jFrame1 = new javax.swing.JFrame();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton130 = new javax.swing.JButton();
        jButton131 = new javax.swing.JButton();
        jButton133 = new javax.swing.JButton();
        jButton134 = new javax.swing.JButton();
        jButton136 = new javax.swing.JButton();
        jButton140 = new javax.swing.JButton();
        jButton143 = new javax.swing.JButton();
        jButton145 = new javax.swing.JButton();
        jButton194 = new javax.swing.JButton();
        jButton195 = new javax.swing.JButton();
        jButton196 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jButton197 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton198 = new javax.swing.JButton();
        jButton199 = new javax.swing.JButton();
        jButton200 = new javax.swing.JButton();
        jButton201 = new javax.swing.JButton();
        jButton202 = new javax.swing.JButton();
        jButton203 = new javax.swing.JButton();
        jButton204 = new javax.swing.JButton();
        jButton205 = new javax.swing.JButton();
        jButton206 = new javax.swing.JButton();
        jButton207 = new javax.swing.JButton();
        jButton208 = new javax.swing.JButton();
        jButton209 = new javax.swing.JButton();
        jButton210 = new javax.swing.JButton();
        jButton211 = new javax.swing.JButton();
        jButton212 = new javax.swing.JButton();
        jButton213 = new javax.swing.JButton();
        jButton214 = new javax.swing.JButton();
        jButton215 = new javax.swing.JButton();
        jButton216 = new javax.swing.JButton();
        jButton217 = new javax.swing.JButton();
        jButton218 = new javax.swing.JButton();
        jButton219 = new javax.swing.JButton();
        jButton220 = new javax.swing.JButton();
        jButton221 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton222 = new javax.swing.JButton();
        jButton223 = new javax.swing.JButton();
        jButton224 = new javax.swing.JButton();
        jButton225 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton226 = new javax.swing.JButton();
        jButton227 = new javax.swing.JButton();
        jButton228 = new javax.swing.JButton();
        jButton229 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton230 = new javax.swing.JButton();
        jButton231 = new javax.swing.JButton();
        jButton232 = new javax.swing.JButton();
        jButton233 = new javax.swing.JButton();
        jButton234 = new javax.swing.JButton();
        jButton235 = new javax.swing.JButton();
        jButton236 = new javax.swing.JButton();
        jButton237 = new javax.swing.JButton();
        jButton238 = new javax.swing.JButton();
        jButton239 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton240 = new javax.swing.JButton();
        jButton241 = new javax.swing.JButton();
        jButton242 = new javax.swing.JButton();
        jButton243 = new javax.swing.JButton();
        jButton244 = new javax.swing.JButton();
        jButton245 = new javax.swing.JButton();
        jButton246 = new javax.swing.JButton();
        jButton247 = new javax.swing.JButton();
        jButton248 = new javax.swing.JButton();
        jButton249 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton250 = new javax.swing.JButton();
        jButton251 = new javax.swing.JButton();
        jButton252 = new javax.swing.JButton();
        jButton253 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton254 = new javax.swing.JButton();
        jButton255 = new javax.swing.JButton();
        jButton256 = new javax.swing.JButton();
        jButton257 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton258 = new javax.swing.JButton();
        jButton259 = new javax.swing.JButton();
        jButton260 = new javax.swing.JButton();
        jButton261 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton262 = new javax.swing.JButton();
        jButton263 = new javax.swing.JButton();
        jButton264 = new javax.swing.JButton();
        jButton265 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jButton266 = new javax.swing.JButton();
        jButton267 = new javax.swing.JButton();
        jButton268 = new javax.swing.JButton();
        jButton269 = new javax.swing.JButton();
        jButton270 = new javax.swing.JButton();
        jButton271 = new javax.swing.JButton();
        jButton272 = new javax.swing.JButton();
        jButton273 = new javax.swing.JButton();
        jButton274 = new javax.swing.JButton();
        jButton275 = new javax.swing.JButton();
        jButton276 = new javax.swing.JButton();
        jButton277 = new javax.swing.JButton();
        jButton278 = new javax.swing.JButton();
        jButton279 = new javax.swing.JButton();
        jButton280 = new javax.swing.JButton();
        jButton281 = new javax.swing.JButton();
        jButton282 = new javax.swing.JButton();
        jButton283 = new javax.swing.JButton();
        jButton284 = new javax.swing.JButton();
        jButton285 = new javax.swing.JButton();
        jButton286 = new javax.swing.JButton();
        jButton287 = new javax.swing.JButton();
        jButton288 = new javax.swing.JButton();
        jButton289 = new javax.swing.JButton();
        jButton290 = new javax.swing.JButton();
        jButton291 = new javax.swing.JButton();
        jButton292 = new javax.swing.JButton();
        jButton293 = new javax.swing.JButton();
        jButton294 = new javax.swing.JButton();
        jButton295 = new javax.swing.JButton();
        jButton296 = new javax.swing.JButton();
        jButton297 = new javax.swing.JButton();
        jButton322 = new javax.swing.JButton();
        jButton323 = new javax.swing.JButton();
        jButton324 = new javax.swing.JButton();
        jButton325 = new javax.swing.JButton();
        jButton326 = new javax.swing.JButton();
        jButton327 = new javax.swing.JButton();
        jButton328 = new javax.swing.JButton();
        jButton329 = new javax.swing.JButton();
        jButton330 = new javax.swing.JButton();
        jButton331 = new javax.swing.JButton();
        jButton332 = new javax.swing.JButton();
        jButton333 = new javax.swing.JButton();
        jButton334 = new javax.swing.JButton();
        jButton335 = new javax.swing.JButton();
        jButton336 = new javax.swing.JButton();
        jButton337 = new javax.swing.JButton();
        jButton338 = new javax.swing.JButton();
        jButton339 = new javax.swing.JButton();
        jButton340 = new javax.swing.JButton();
        jButton341 = new javax.swing.JButton();
        jButton342 = new javax.swing.JButton();
        jButton343 = new javax.swing.JButton();
        jButton344 = new javax.swing.JButton();
        jButton345 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton9.setText("4");

        jButton7.setText("5");

        jButton10.setText("6");

        jButton11.setText("7");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("10");

        jButton13.setText("11");

        jButton14.setText("12");

        jButton15.setText("8");

        jButton16.setText("9");

        jButton18.setText("14");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("15");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("16");

        jButton22.setText("13");

        jButton130.setText("7");
        jButton130.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton130ActionPerformed(evt);
            }
        });

        jButton131.setText("8");

        jButton133.setText("2");
        jButton133.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton133ActionPerformed(evt);
            }
        });

        jButton134.setText("3");

        jButton136.setText("1");

        jButton140.setText("4");

        jButton143.setText("5");

        jButton145.setText("6");

        jButton194.setText("1");

        jButton195.setText("2");

        jButton196.setText("3");

        jButton1.setText("Issue Tickets");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panel1.setLayout(new java.awt.GridBagLayout());

        jButton197.setText("4");

        jButton8.setText("5");

        jButton198.setText("6");

        jButton199.setText("7");
        jButton199.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton199ActionPerformed(evt);
            }
        });

        jButton200.setText("10");

        jButton201.setText("11");

        jButton202.setText("12");

        jButton203.setText("8");

        jButton204.setText("9");

        jButton205.setText("14");

        jButton206.setText("15");

        jButton207.setText("16");

        jButton208.setText("13");

        jButton209.setText("1");

        jButton210.setText("2");

        jButton211.setText("3");

        jButton212.setText("6");

        jButton213.setText("7");
        jButton213.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton213ActionPerformed(evt);
            }
        });

        jButton214.setText("10");

        jButton215.setText("11");

        jButton216.setText("12");

        jButton217.setText("8");

        jButton218.setText("9");

        jButton219.setText("14");

        jButton220.setText("15");

        jButton221.setText("16");

        jButton17.setText("4");

        jButton21.setText("5");

        jButton23.setText("6");

        jButton24.setText("7");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setText("10");

        jButton26.setText("11");

        jButton27.setText("12");

        jButton28.setText("8");

        jButton222.setText("13");

        jButton223.setText("1");

        jButton224.setText("2");

        jButton225.setText("3");

        jButton29.setText("9");

        jButton30.setText("14");

        jButton31.setText("15");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setText("16");

        jButton33.setText("13");

        jButton226.setText("1");

        jButton227.setText("2");

        jButton228.setText("3");

        jButton229.setText("4");

        jButton34.setText("5");

        jButton230.setText("6");

        jButton231.setText("7");
        jButton231.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton231ActionPerformed(evt);
            }
        });

        jButton232.setText("10");

        jButton233.setText("11");

        jButton234.setText("12");

        jButton235.setText("8");

        jButton236.setText("9");

        jButton237.setText("14");

        jButton238.setText("15");

        jButton239.setText("16");

        jButton35.setText("4");

        jButton36.setText("5");

        jButton37.setText("6");

        jButton38.setText("7");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        jButton39.setText("10");

        jButton40.setText("11");

        jButton41.setText("12");

        jButton42.setText("8");

        jButton240.setText("13");

        jButton241.setText("1");

        jButton242.setText("2");

        jButton243.setText("3");

        jButton244.setText("6");

        jButton245.setText("7");
        jButton245.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton245ActionPerformed(evt);
            }
        });

        jButton246.setText("10");

        jButton247.setText("11");

        jButton248.setText("12");

        jButton249.setText("8");

        jButton43.setText("9");

        jButton44.setText("14");

        jButton45.setText("15");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });

        jButton46.setText("16");

        jButton47.setText("13");

        jButton250.setText("9");

        jButton251.setText("14");

        jButton252.setText("15");

        jButton253.setText("16");

        jButton48.setText("4");

        jButton49.setText("5");

        jButton50.setText("6");

        jButton51.setText("7");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });

        jButton52.setText("10");

        jButton53.setText("11");

        jButton54.setText("12");

        jButton55.setText("8");

        jButton254.setText("13");

        jButton255.setText("1");

        jButton256.setText("2");

        jButton257.setText("3");

        jButton56.setText("9");

        jButton57.setText("14");

        jButton58.setText("15");
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });

        jButton59.setText("16");

        jButton60.setText("13");

        jButton258.setText("1");

        jButton259.setText("2");

        jButton260.setText("3");

        jButton261.setText("4");

        jButton61.setText("5");

        jButton262.setText("1");

        jButton263.setText("2");

        jButton264.setText("3");

        jButton265.setText("4");

        jButton62.setText("5");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jButton1, org.jdesktop.beansbinding.ELProperty.create("BOOKED:"), jTextPane1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane3.setViewportView(jTextPane1);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jButton1, org.jdesktop.beansbinding.ELProperty.create("TOTAL:"), jTextPane2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane4.setViewportView(jTextPane2);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jButton1, org.jdesktop.beansbinding.ELProperty.create("VACANT:"), jTextPane3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane5.setViewportView(jTextPane3);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jButton1, org.jdesktop.beansbinding.ELProperty.create("SELECTED:"), jTextPane4, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane6.setViewportView(jTextPane4);

        jTextField1.setText("                                                                                                         SCREEN");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton266.setText("7");
        jButton266.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton266ActionPerformed(evt);
            }
        });

        jButton267.setText("8");

        jButton268.setText("2");
        jButton268.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton268ActionPerformed(evt);
            }
        });

        jButton269.setText("3");

        jButton270.setText("1");

        jButton271.setText("4");

        jButton272.setText("5");

        jButton273.setText("6");

        jButton274.setText("7");
        jButton274.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton274ActionPerformed(evt);
            }
        });

        jButton275.setText("8");

        jButton276.setText("2");
        jButton276.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton276ActionPerformed(evt);
            }
        });

        jButton277.setText("3");

        jButton278.setText("1");

        jButton279.setText("4");

        jButton280.setText("5");

        jButton281.setText("6");

        jButton282.setText("7");
        jButton282.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton282ActionPerformed(evt);
            }
        });

        jButton283.setText("8");

        jButton284.setText("2");
        jButton284.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton284ActionPerformed(evt);
            }
        });

        jButton285.setText("3");

        jButton286.setText("1");

        jButton287.setText("4");

        jButton288.setText("5");

        jButton289.setText("6");

        jButton290.setText("15");
        jButton290.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton290ActionPerformed(evt);
            }
        });

        jButton291.setText("16");

        jButton292.setText("10");
        jButton292.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton292ActionPerformed(evt);
            }
        });

        jButton293.setText("11");

        jButton294.setText("9");
        jButton294.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton294ActionPerformed(evt);
            }
        });

        jButton295.setText("12");

        jButton296.setText("13");

        jButton297.setText("14");

        jButton322.setText("15");
        jButton322.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton322ActionPerformed(evt);
            }
        });

        jButton323.setText("16");

        jButton324.setText("10");
        jButton324.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton324ActionPerformed(evt);
            }
        });

        jButton325.setText("11");

        jButton326.setText("9");
        jButton326.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton326ActionPerformed(evt);
            }
        });

        jButton327.setText("12");

        jButton328.setText("13");

        jButton329.setText("14");

        jButton330.setText("15");
        jButton330.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton330ActionPerformed(evt);
            }
        });

        jButton331.setText("16");

        jButton332.setText("10");
        jButton332.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton332ActionPerformed(evt);
            }
        });

        jButton333.setText("11");

        jButton334.setText("9");
        jButton334.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton334ActionPerformed(evt);
            }
        });

        jButton335.setText("12");

        jButton336.setText("13");

        jButton337.setText("14");

        jButton338.setText("15");
        jButton338.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton338ActionPerformed(evt);
            }
        });

        jButton339.setText("16");

        jButton340.setText("10");
        jButton340.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton340ActionPerformed(evt);
            }
        });

        jButton341.setText("11");

        jButton342.setText("9");
        jButton342.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton342ActionPerformed(evt);
            }
        });

        jButton343.setText("12");

        jButton344.setText("13");

        jButton345.setText("14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton194)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton195)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton196))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton209)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton210)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton211))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton223)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton224)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton225))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton226)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton227)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton228))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton241)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton242)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton243))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton255)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton256)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton257))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton258)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton259)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton260))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton262)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton263)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton264)))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton9)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton7)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton10)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton11)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton15)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton16)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton12)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton13)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton197)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton8)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton198)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton199)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton203)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton204)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton200)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton201)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton202)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton208))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton229)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton34)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton212)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton213)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton217)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton218)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton214)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton215)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton216)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton222))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton17)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton21)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton23)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton24)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton28)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton29)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton25)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton26)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton33))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton265)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton62)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton230)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton231)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton235)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton236)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton232)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton233)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton234)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton240))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton35)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton36)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton37)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton38)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton42)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton43)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton39)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton40)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton47))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton261)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton61)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton244)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton245)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton249)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton250)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton246)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton247)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton248)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton254))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton48)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton49)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton50)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton51)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton55)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton56)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton52)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton53)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton54)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton60)))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton18)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton19)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton20))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton205)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton206)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton207))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton30)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton31)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton32))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton237)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton238)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton239))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton44)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton45)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton46))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton251)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton252)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton253))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton57)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton58)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton59))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(200, 200, 200)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane4)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton219)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton220)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton221)
                                        .addGap(39, 39, 39)
                                        .addComponent(jScrollPane6))))
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton136)
                                .addGap(10, 10, 10)
                                .addComponent(jButton133)
                                .addGap(10, 10, 10)
                                .addComponent(jButton134)
                                .addGap(10, 10, 10)
                                .addComponent(jButton140)
                                .addGap(10, 10, 10)
                                .addComponent(jButton143)
                                .addGap(10, 10, 10)
                                .addComponent(jButton145)
                                .addGap(10, 10, 10)
                                .addComponent(jButton130)
                                .addGap(10, 10, 10)
                                .addComponent(jButton131))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton278)
                                .addGap(10, 10, 10)
                                .addComponent(jButton276)
                                .addGap(10, 10, 10)
                                .addComponent(jButton277)
                                .addGap(10, 10, 10)
                                .addComponent(jButton279)
                                .addGap(10, 10, 10)
                                .addComponent(jButton280)
                                .addGap(10, 10, 10)
                                .addComponent(jButton281)
                                .addGap(10, 10, 10)
                                .addComponent(jButton274)
                                .addGap(10, 10, 10)
                                .addComponent(jButton275))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton286)
                                .addGap(10, 10, 10)
                                .addComponent(jButton284)
                                .addGap(10, 10, 10)
                                .addComponent(jButton285)
                                .addGap(10, 10, 10)
                                .addComponent(jButton287)
                                .addGap(10, 10, 10)
                                .addComponent(jButton288)
                                .addGap(10, 10, 10)
                                .addComponent(jButton289)
                                .addGap(10, 10, 10)
                                .addComponent(jButton282)
                                .addGap(10, 10, 10)
                                .addComponent(jButton283))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton270)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton268)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton269)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton271)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton272)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton273)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton266)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton267)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton326)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton324)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton325)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton327)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton328)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton329)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton322)
                                        .addGap(10, 10, 10)
                                        .addComponent(jButton323))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(469, 469, 469)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton294)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton292)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton293)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton295)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton296)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton297)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton290)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton291))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton334)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton332)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton333)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton335)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton336)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton337)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton330)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton331))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton342)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton340)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton341)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton343)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton344)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton345)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton338)
                                                .addGap(10, 10, 10)
                                                .addComponent(jButton339)))))
                                .addGap(242, 242, 242)))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton7)
                                .addComponent(jButton10)
                                .addComponent(jButton9)
                                .addComponent(jButton15)
                                .addComponent(jButton16)
                                .addComponent(jButton11)
                                .addComponent(jButton13)
                                .addComponent(jButton14)
                                .addComponent(jButton12)
                                .addComponent(jButton22)
                                .addComponent(jButton19)
                                .addComponent(jButton20)
                                .addComponent(jButton18)
                                .addComponent(jButton195)
                                .addComponent(jButton196)
                                .addComponent(jButton194))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton8)
                                .addComponent(jButton198)
                                .addComponent(jButton197)
                                .addComponent(jButton203)
                                .addComponent(jButton204)
                                .addComponent(jButton199)
                                .addComponent(jButton201)
                                .addComponent(jButton202)
                                .addComponent(jButton200)
                                .addComponent(jButton208)
                                .addComponent(jButton206)
                                .addComponent(jButton207)
                                .addComponent(jButton205)
                                .addComponent(jButton210)
                                .addComponent(jButton211)
                                .addComponent(jButton209))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton21)
                                .addComponent(jButton23)
                                .addComponent(jButton17)
                                .addComponent(jButton28)
                                .addComponent(jButton29)
                                .addComponent(jButton24)
                                .addComponent(jButton26)
                                .addComponent(jButton27)
                                .addComponent(jButton25)
                                .addComponent(jButton33)
                                .addComponent(jButton31)
                                .addComponent(jButton32)
                                .addComponent(jButton30)
                                .addComponent(jButton227)
                                .addComponent(jButton228)
                                .addComponent(jButton226))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton34)
                            .addComponent(jButton212)
                            .addComponent(jButton229)
                            .addComponent(jButton217)
                            .addComponent(jButton218)
                            .addComponent(jButton213)
                            .addComponent(jButton215)
                            .addComponent(jButton216)
                            .addComponent(jButton214)
                            .addComponent(jButton222)
                            .addComponent(jButton220)
                            .addComponent(jButton221)
                            .addComponent(jButton219)
                            .addComponent(jButton224)
                            .addComponent(jButton225)
                            .addComponent(jButton223)))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton36)
                    .addComponent(jButton37)
                    .addComponent(jButton35)
                    .addComponent(jButton42)
                    .addComponent(jButton43)
                    .addComponent(jButton38)
                    .addComponent(jButton40)
                    .addComponent(jButton41)
                    .addComponent(jButton39)
                    .addComponent(jButton47)
                    .addComponent(jButton45)
                    .addComponent(jButton46)
                    .addComponent(jButton44)
                    .addComponent(jButton263)
                    .addComponent(jButton264)
                    .addComponent(jButton262))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton62)
                    .addComponent(jButton230)
                    .addComponent(jButton265)
                    .addComponent(jButton235)
                    .addComponent(jButton236)
                    .addComponent(jButton231)
                    .addComponent(jButton233)
                    .addComponent(jButton234)
                    .addComponent(jButton232)
                    .addComponent(jButton240)
                    .addComponent(jButton238)
                    .addComponent(jButton239)
                    .addComponent(jButton237)
                    .addComponent(jButton242)
                    .addComponent(jButton243)
                    .addComponent(jButton241))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton49)
                    .addComponent(jButton50)
                    .addComponent(jButton48)
                    .addComponent(jButton55)
                    .addComponent(jButton56)
                    .addComponent(jButton51)
                    .addComponent(jButton53)
                    .addComponent(jButton54)
                    .addComponent(jButton52)
                    .addComponent(jButton60)
                    .addComponent(jButton58)
                    .addComponent(jButton59)
                    .addComponent(jButton57)
                    .addComponent(jButton259)
                    .addComponent(jButton260)
                    .addComponent(jButton258))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton61)
                    .addComponent(jButton244)
                    .addComponent(jButton261)
                    .addComponent(jButton249)
                    .addComponent(jButton250)
                    .addComponent(jButton245)
                    .addComponent(jButton247)
                    .addComponent(jButton248)
                    .addComponent(jButton246)
                    .addComponent(jButton254)
                    .addComponent(jButton252)
                    .addComponent(jButton253)
                    .addComponent(jButton251)
                    .addComponent(jButton256)
                    .addComponent(jButton257)
                    .addComponent(jButton255))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton133)
                            .addComponent(jButton134)
                            .addComponent(jButton136)
                            .addComponent(jButton143)
                            .addComponent(jButton145)
                            .addComponent(jButton140)
                            .addComponent(jButton131)
                            .addComponent(jButton130))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton268)
                            .addComponent(jButton269)
                            .addComponent(jButton270)
                            .addComponent(jButton272)
                            .addComponent(jButton273)
                            .addComponent(jButton271)
                            .addComponent(jButton267)
                            .addComponent(jButton266))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton276)
                            .addComponent(jButton277)
                            .addComponent(jButton278)
                            .addComponent(jButton280)
                            .addComponent(jButton281)
                            .addComponent(jButton279)
                            .addComponent(jButton275)
                            .addComponent(jButton274))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton284)
                            .addComponent(jButton285)
                            .addComponent(jButton286)
                            .addComponent(jButton288)
                            .addComponent(jButton289)
                            .addComponent(jButton287)
                            .addComponent(jButton283)
                            .addComponent(jButton282)))
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton292)
                            .addComponent(jButton293)
                            .addComponent(jButton294)
                            .addComponent(jButton296)
                            .addComponent(jButton297)
                            .addComponent(jButton295)
                            .addComponent(jButton291)
                            .addComponent(jButton290))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton324)
                            .addComponent(jButton325)
                            .addComponent(jButton326)
                            .addComponent(jButton328)
                            .addComponent(jButton329)
                            .addComponent(jButton327)
                            .addComponent(jButton323)
                            .addComponent(jButton322))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton332)
                            .addComponent(jButton333)
                            .addComponent(jButton334)
                            .addComponent(jButton336)
                            .addComponent(jButton337)
                            .addComponent(jButton335)
                            .addComponent(jButton331)
                            .addComponent(jButton330))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton340)
                            .addComponent(jButton341)
                            .addComponent(jButton342)
                            .addComponent(jButton344)
                            .addComponent(jButton345)
                            .addComponent(jButton343)
                            .addComponent(jButton339)
                            .addComponent(jButton338))))
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton130ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton130ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton130ActionPerformed

    private void jButton199ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton199ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton199ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton213ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton213ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton213ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton231ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton231ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton231ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton245ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton245ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton245ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton133ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton133ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton133ActionPerformed

    private void jButton266ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton266ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton266ActionPerformed

    private void jButton268ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton268ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton268ActionPerformed

    private void jButton274ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton274ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton274ActionPerformed

    private void jButton276ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton276ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton276ActionPerformed

    private void jButton282ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton282ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton282ActionPerformed

    private void jButton284ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton284ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton284ActionPerformed

    private void jButton290ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton290ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton290ActionPerformed

    private void jButton292ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton292ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton292ActionPerformed

    private void jButton294ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton294ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton294ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton322ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton322ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton322ActionPerformed

    private void jButton324ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton324ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton324ActionPerformed

    private void jButton326ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton326ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton326ActionPerformed

    private void jButton330ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton330ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton330ActionPerformed

    private void jButton332ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton332ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton332ActionPerformed

    private void jButton334ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton334ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton334ActionPerformed

    private void jButton338ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton338ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton338ActionPerformed

    private void jButton340ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton340ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton340ActionPerformed

    private void jButton342ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton342ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton342ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new java().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton130;
    private javax.swing.JButton jButton131;
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton134;
    private javax.swing.JButton jButton136;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton140;
    private javax.swing.JButton jButton143;
    private javax.swing.JButton jButton145;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton194;
    private javax.swing.JButton jButton195;
    private javax.swing.JButton jButton196;
    private javax.swing.JButton jButton197;
    private javax.swing.JButton jButton198;
    private javax.swing.JButton jButton199;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton200;
    private javax.swing.JButton jButton201;
    private javax.swing.JButton jButton202;
    private javax.swing.JButton jButton203;
    private javax.swing.JButton jButton204;
    private javax.swing.JButton jButton205;
    private javax.swing.JButton jButton206;
    private javax.swing.JButton jButton207;
    private javax.swing.JButton jButton208;
    private javax.swing.JButton jButton209;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton210;
    private javax.swing.JButton jButton211;
    private javax.swing.JButton jButton212;
    private javax.swing.JButton jButton213;
    private javax.swing.JButton jButton214;
    private javax.swing.JButton jButton215;
    private javax.swing.JButton jButton216;
    private javax.swing.JButton jButton217;
    private javax.swing.JButton jButton218;
    private javax.swing.JButton jButton219;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton220;
    private javax.swing.JButton jButton221;
    private javax.swing.JButton jButton222;
    private javax.swing.JButton jButton223;
    private javax.swing.JButton jButton224;
    private javax.swing.JButton jButton225;
    private javax.swing.JButton jButton226;
    private javax.swing.JButton jButton227;
    private javax.swing.JButton jButton228;
    private javax.swing.JButton jButton229;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton230;
    private javax.swing.JButton jButton231;
    private javax.swing.JButton jButton232;
    private javax.swing.JButton jButton233;
    private javax.swing.JButton jButton234;
    private javax.swing.JButton jButton235;
    private javax.swing.JButton jButton236;
    private javax.swing.JButton jButton237;
    private javax.swing.JButton jButton238;
    private javax.swing.JButton jButton239;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton240;
    private javax.swing.JButton jButton241;
    private javax.swing.JButton jButton242;
    private javax.swing.JButton jButton243;
    private javax.swing.JButton jButton244;
    private javax.swing.JButton jButton245;
    private javax.swing.JButton jButton246;
    private javax.swing.JButton jButton247;
    private javax.swing.JButton jButton248;
    private javax.swing.JButton jButton249;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton250;
    private javax.swing.JButton jButton251;
    private javax.swing.JButton jButton252;
    private javax.swing.JButton jButton253;
    private javax.swing.JButton jButton254;
    private javax.swing.JButton jButton255;
    private javax.swing.JButton jButton256;
    private javax.swing.JButton jButton257;
    private javax.swing.JButton jButton258;
    private javax.swing.JButton jButton259;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton260;
    private javax.swing.JButton jButton261;
    private javax.swing.JButton jButton262;
    private javax.swing.JButton jButton263;
    private javax.swing.JButton jButton264;
    private javax.swing.JButton jButton265;
    private javax.swing.JButton jButton266;
    private javax.swing.JButton jButton267;
    private javax.swing.JButton jButton268;
    private javax.swing.JButton jButton269;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton270;
    private javax.swing.JButton jButton271;
    private javax.swing.JButton jButton272;
    private javax.swing.JButton jButton273;
    private javax.swing.JButton jButton274;
    private javax.swing.JButton jButton275;
    private javax.swing.JButton jButton276;
    private javax.swing.JButton jButton277;
    private javax.swing.JButton jButton278;
    private javax.swing.JButton jButton279;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton280;
    private javax.swing.JButton jButton281;
    private javax.swing.JButton jButton282;
    private javax.swing.JButton jButton283;
    private javax.swing.JButton jButton284;
    private javax.swing.JButton jButton285;
    private javax.swing.JButton jButton286;
    private javax.swing.JButton jButton287;
    private javax.swing.JButton jButton288;
    private javax.swing.JButton jButton289;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton290;
    private javax.swing.JButton jButton291;
    private javax.swing.JButton jButton292;
    private javax.swing.JButton jButton293;
    private javax.swing.JButton jButton294;
    private javax.swing.JButton jButton295;
    private javax.swing.JButton jButton296;
    private javax.swing.JButton jButton297;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton322;
    private javax.swing.JButton jButton323;
    private javax.swing.JButton jButton324;
    private javax.swing.JButton jButton325;
    private javax.swing.JButton jButton326;
    private javax.swing.JButton jButton327;
    private javax.swing.JButton jButton328;
    private javax.swing.JButton jButton329;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton330;
    private javax.swing.JButton jButton331;
    private javax.swing.JButton jButton332;
    private javax.swing.JButton jButton333;
    private javax.swing.JButton jButton334;
    private javax.swing.JButton jButton335;
    private javax.swing.JButton jButton336;
    private javax.swing.JButton jButton337;
    private javax.swing.JButton jButton338;
    private javax.swing.JButton jButton339;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton340;
    private javax.swing.JButton jButton341;
    private javax.swing.JButton jButton342;
    private javax.swing.JButton jButton343;
    private javax.swing.JButton jButton344;
    private javax.swing.JButton jButton345;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private java.awt.Panel panel1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
